; -*- lexical-binding: t -*-

; x-release-please-start-version
(package "brushup" "0.1.2" "Dynamic theme-aware color palette")
; x-release-please-end
(website-url "https://github.com/chiply/brushup")
(keywords "faces" "themes")
(package-file "brushup.el")
(files "brushup.el")
(script "test" "eask test ert test/brushup-test.el")
(source "gnu")
(source "melpa")
(depends-on "emacs" "29.1")
(development
 (depends-on "package-lint")
 (depends-on "elisp-lint")
 (depends-on "relint"))
